//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Inventory
{
    using System;
    using System.Collections.Generic;
    
    public partial class Inventory
    {
        public int Id { get; set; }
        public string Handle { get; set; }
        public string Title { get; set; }
        public string Body__HTML_ { get; set; }
        public string Type { get; set; }
        public string Tags { get; set; }
        public Nullable<bool> Published { get; set; }
        public string Option1_Name { get; set; }
        public string Option1_Value { get; set; }
        public string Option2_Name { get; set; }
        public string Option2_Value { get; set; }
        public string Option3_Name { get; set; }
        public string Option3_Value { get; set; }
        public Nullable<double> Original_Price { get; set; }
        public string Variant_SKU { get; set; }
        public Nullable<double> Variant_Price { get; set; }
        public Nullable<int> Variant_Inventory { get; set; }
        public Nullable<int> Qty { get; set; }
        public Nullable<bool> Variant_Taxable { get; set; }
        public string Vendor { get; set; }
        public string VendorShort { get; set; }
        public string Lead_Time { get; set; }
        public string MOQ { get; set; }
        public string Condition { get; set; }
        public string Collection { get; set; }
        public string SEO_Title { get; set; }
        public string SEO_Description { get; set; }
        public string Image_Src { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
        public string fob { get; set; }
        public string Certification { get; set; }
        public string Dimensions { get; set; }
        public string Notes { get; set; }
        public string Technical_Documentation { get; set; }
        public string tax_class_id { get { return "None"; } }
        public string is_in_stock { get { return "In Stock"; } }
        public string weight { get { return "0.0000"; } }
        public string combine { get
            {
                return this.Condition + "::" + this.fob + "::" + this.Certification + "::" + this.Lead_Time;
                    }

        }

        public string category {  get { return "Aircraft Parts"; } }
    }
}
